- name: Install NGINX
  ansible.builtin.apt:
    name: nginx
    state: present
  notify: Restart NGINX
- name: Copy NGINX templates
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart NGINX
- name: Start NGINX
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
- name: Install PHP-FPM
  ansible.builtin.apt:
    name: 
      - php8.3-fpm
      - php8.3-mysql
      - php8.3-mbstring
    state: present
  notify: Restart PHP-FPM
- name: Start PHP-FPM and enabled it
  ansible.builtin.service:
    name: php8.3-fpm
    state: started
    enabled: true
- name: Install Git
  ansible.builtin.apt:
    name: git
    state: present
- name: Clone php project
  ansible.builtin.git:
    repo: 'https://github.com/dymafr/ansible-projet2.git'
    dest: /var/www/app
    update: true